From java:8-jre
WORKDIR usr/lib
ADD ./target/orchestrationService-0.0.1-SNAPSHOT.jar /usr/lib/orchestrationService-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","orchestrationService-0.0.1-SNAPSHOT.jar"]

